version: '3.1'
services:
  at_server:
    image: klotzandrew/at_server
    ports:
      - "5000:5000"
    environment:
      CLIENT_PORT: 5000
      SERVER_HOST: activetick1.activetick.com
      API_KEY: ${API_KEY}
      AT_USER_ID: ${AT_USER_ID}
      AT_PASSWORD: ${AT_PASSWORD}
